body:
  - type: markdown
    attributes:
      value: |
        ## SOLAPI 개발연동 Q&A
        SDK 혹은 개발연동 관련 질문을 작성하기 전에 [SOLAPI 문서](https://developers.solapi.com/)와 이전 토론을 확인해보세요.
        
  - type: input
    id: sdk-language
    attributes:
      label: 사용 중인 프로그래밍 언어 및 버전
      description: 예시) Node.js v16.13.0, PHP 8.1, Python 3.9 등
      placeholder: Node.js v18.12.0
    validations:
      required: true
      
  - type: input
    id: sdk-version
    attributes:
      label: SDK 버전
      description: 사용 중인 SDK 버전을 입력해주세요
      placeholder: SOLAPI Node.js SDK v5.4.0 등
    validations:
      required: false
      
  - type: dropdown
    id: environment
    attributes:
      label: 운영 환경
      description: 어떤 환경에서 실행 중인가요?
      options:
        - 개발 환경 (로컬)        
        - AWS/클라우드/호스팅 서버 등 상용 웹 서버
        - 기타 (설명란에 자세히 기재해주세요)
    validations:
      required: true
      
  - type: textarea
    id: question
    attributes:
      label: 질문/문제 설명
      description: SDK 사용 중 발생한 문제나 질문을 자세히 작성해주세요
      placeholder: |
        여기에 문제나 질문을 자세히 설명해주세요.
        
        구현하려는 기능:
        발생한 오류 메시지 (있는 경우):
    validations:
      required: true
      
  - type: textarea
    id: code
    attributes:
      label: 코드 예시
      description: 문제가 발생한 코드를 공유해주세요. 단, 민감 정보는 반드시 제거해야합니다(예) api key, api secret key 등)
      render: javascript
      placeholder: |
        // 예시 코드
        const {SolapiMessageService} = require('solapi');
        const messageService = new SolapiMessageService(
          'ENTER_YOUR_API_KEY',
          'ENTER_YOUR_API_SECRET',
        );
        
        // 단일 발송 예제, send 메소드로도 동일하게 사용가능
        messageService
          .send({
            to: '수신번호',
            from: '계정에서 등록한 발신번호 입력',
            text: '한글 45자, 영자 90자 이하 입력되면 자동으로 SMS타입의 메시지가 발송됩니다.',
          })
          .then(res => console.log(res));      
    validations:
      required: false
      
  - type: textarea
    id: attempted
    attributes:
      label: 시도한 해결 방법
      description: 이 문제를 해결하기 위해 이미 시도해 본 방법이 있다면 작성해주세요
      placeholder: |
        1. 이 방법을 시도해봤습니다...
        2. 문서에서 이 부분을 확인했습니다...
    validations:
      required: false
      
  - type: textarea
    id: expected
    attributes:
      label: 기대하는 결과
      description: 원하는 결과나 기대하는 동작을 설명해주세요
      placeholder: 메시지가 성공적으로 전송되어야 합니다...
    validations:
      required: true
      
  - type: checkboxes
    id: terms
    attributes:
      label: 확인사항
      description: 질문을 제출하기 전에 다음 항목을 확인해주세요
      options:
        - label: 관련 문서를 확인했습니다
          required: true
        - label: 이전 토론/이슈에서 유사한 질문이 없는지 확인했습니다
          required: true
